### ISSUE TITLE
Oreo: FC, factory reset, straight boot to TWRP

### ISSUE THREAD

**Issue by pokipokipxorn** [james34602/JamesDSPManager#10]
Installed Nov 3rd build on Oreo, using TWRP method. Upon boot, JamesDSP will FC, factory reset & boot straight into TWRP. But on Nougat, JamesDSP is working well, thank you.

**Comment by james34602** [comment]
I had update the page, Android 8.0 is not supported yet.
Since it cannot test by emulator in SDK.
I need a device with Android 8.0 to test, but this won't be quick.

**Comment by skittles9823** [comment]
James I'd be willing to test builds on Oreo if you like. I found out that if it's installed as a user app it won't constantly force close and I can actually open it without it crashing however a toast appears saying "DSP module crashed".

**Comment by james34602** [comment]
Thanks for help!
I will upload some modifications which add more debug messages.
The toast message "DSP module crashed" doesn't mean it actually crashed, you definitely could assist me to debug!
Some clue to debug, for normal installation:
1. Install APK
2. Replace/Modify audio_effects.conf to add jamesdsp line
3. Rename libjamesdspDebug.so to libjamesdsp.so
4. Copy .so to /system/soundfx/
5. Reboot and launch apps, record logcat from adb, try changing parameters.

**Comment by skittles9823** [comment]
@james34602 perfect. I'll do that and upload to the XDA thread once you post it.

**Comment by skittles9823** [comment]
@james34602

In the mean time I did the debug steps.

https://drive.google.com/file/d/12TtRDtqljOOzprEecdEglklww-lvObBP/view?usp=drivesdk

I took a full unfiltered catlog since when it was filtered it looks the same as with the regular lib when searching for "James".

**Comment by james34602** [comment]
Good!
However did you using latest APK?

**Comment by skittles9823** [comment]
@james34602

Whoops. Missed the app.

https://drive.google.com/file/d/19TrtLOVkSf_0UhN9LKQWa1Vx37NEdxbn/view?usp=drivesdk

Here is a new catlog.

**Comment by james34602** [comment]
I see.
You are testing bass boost, and it crashed when initialising convolution engine.
I probably make a more detailed log in linear phase bass boost refreshing.

**Comment by skittles9823** [comment]
Yea. The main things I'll be using are the bass boost and convolution. Currently yet to actually have it work as even on Nougat it wasn't working for me. (However I didn't debug it too much then).

**Comment by james34602** [comment]
I found that program fail to obtain buffer length, which is a fatal error.
This patch may not / don't expect will gonna solve this, but it will print more verbose log.
[libjamesdsp.zip](https://github.com/james34602/JamesDSPManager/files/1517269/libjamesdsp.zip)
Use email as possible! Otherwise this page will be so long.

**Comment by skittles9823** [comment]
@james34602

Okay. I'll try this when I'm home. If you have Telegram then that would be even easier to discuss this, if not I'll email (my telegram is @Skittles9823)

**Comment by james34602** [comment]
Probably solved in latest release, but it require more step.
