### ISSUE TITLE
SoundCloud doesn't seem to work.

### ISSUE THREAD

**Issue by updatesvc** [james34602/JamesDSPManager#11]
First of all, I would like to say what a great project this is.
When using **Soundcloud** I hear no distinction in the audio, basically its like it bypasses **DSPManager**.
Hope this isn't necessarily a bug , if this is a missing feature hopefully it could be added in one of the future updates.
BTW I tested with **Youtube** and other apps and it works great.

My Environment : 
Nougat Armx64

**Comment by james34602** [comment]
[https://forum.xda-developers.com/android/apps-games/app-soundcloud-compatible-viper4android-t3555613](https://forum.xda-developers.com/android/apps-games/app-soundcloud-compatible-viper4android-t3555613)
This issue same could be solved by modifying system, but use of your own risk.
V4A and JDSP use same mechanism on global audio effect registering.

**Comment by updatesvc** [comment]
Thanks I'll probably just download the songs
