### ISSUE TITLE
htc 10

### ISSUE THREAD

**Issue by JohnFawkes** [james34602/JamesDSPManager#12]
hello james. i know you dont like htc devices for they do something weird with audio framework. anyway i have a htc 10 running viper rom based on sense Nougat 7.0. im using jamesdsp via the aml magisk module. turning master switch on causes audio to get extremely staticy and choppy

**Comment by james34602** [comment]
I'm sorry, I can't debug if nothing crash.
I need some clues.

**Comment by JohnFawkes** [comment]
this happens without ainur. no audio mods installed but jdsp

**Comment by JohnFawkes** [comment]
also it didnt happen when i was running Resurrection remix basd on asop but happens on viper rom based on stock sense

**Comment by james34602** [comment]
I can't test on HTC stock.
You are right AOSP rom work fine, but not stock HTC.
I can only support Samsung, AOSP, and most custom ROM, but not Huawei or HTC, because I don't know what is happening inside your system.

**Comment by JohnFawkes** [comment]
is there any kind of logs i can provide with music playing and jdsp enabled for you to be able to see whats going on?

**Comment by james34602** [comment]
You can record some logcat.

**Comment by JohnFawkes** [comment]
[nomusicplaying.txt](https://github.com/james34602/JamesDSPManager/files/1555223/nomusicplaying.txt)

**Comment by JohnFawkes** [comment]
[musicplaying.txt](https://github.com/james34602/JamesDSPManager/files/1555224/musicplaying.txt)

**Comment by james34602** [comment]
As what I had expect.
Log can't reveal issues.
I will keep my eyes on such devices.

**Comment by JohnFawkes** [comment]
ok. well if you need me to test anything just let me know

**Comment by james34602** [comment]
HTC choppy sound issue have been solved via bit depth handling
