### ISSUE TITLE
Add some presets for equalizer

### ISSUE THREAD

**Issue by morfikov** [james34602/JamesDSPManager#13]
I just installed `JamesDSPManager-v1.5-HQ-Auto.zip` on my phone (TP-Llink Neffos x1 Max, ARM64, Android 7.0) via TWRP recovery, and it looks that it works just fine. I just wanted to ask whether would you add some presets for the equalizer? For now I have to set the frequencies manually, and I'm not good at it. Some applications have the ability to choose something like "rock" or "metal" and it would be nice to have some options like that here.

**Comment by james34602** [comment]
I got it.
You can help me to make your favourite presets!

**Comment by morfikov** [comment]
How can I help you? :)

**Comment by james34602** [comment]
Draw your own eq graph and save as apps preset, find them in your /sdcard/JamesDSP directory.
Whatever, I will find some good preset and interpolate them and add it as JamesDSP eq presets.

**Comment by jianwen03** [comment]
What about the presets in the older releases? May I know why were they removed?

**Comment by james34602** [comment]
If you know the history of JamesDSP, you will know why I did so.
This DSP is a heavily modified from Cyanogenmod DSP Manager, you are no longer recognize the code.
So what about original DSP equalizer? I had only 6 bands, and full constructed by IIR filters. Current implementation is completely than that, so it's preset cannot be used anymore.
