### ISSUE TITLE
Effects Ideas

### ISSUE THREAD

**Issue by uudruid74** [james34602/JamesDSPManager#15]
One of the effects I used to use a lot from pro audio is a harmonic exciter.   It's an attack sensitive circuit that enhances the 16KHz range in response to dynamic attack.  It can really bring things out of a mix.

I'm not sure if Viper's Clarity control is similar, but it sounds like Viper is similar, but maybe a bit lower frequency, maybe even down to 4KHz like a presence control.

Likewise Viper's Subwoofer emulator enhances deeper bass while the dynamic bass controls the dynamic "thump".  Being able to control them both allows for more fine tuning and being able to push the speakers a bit closer to full potential.

Another idea would be a multi-band compressor, where the sound is split into frequency bands and compressed separately before being mixed back together.  This gives more control while also reducing interference between frequency bands.

**Comment by james34602** [comment]
Harmonic bass effect had attract my interest although I don't have much time on current open source version. However audio effect that catch my eye is MaxxBass, which is also a harmonic-based effect.
For multi-band compression, since this is not a studio plugin effect(and never will be), we don't need professional audio effects.

**Comment by james34602** [comment]
Viper did use harmonic excitor on spectrum extension, it will be a coming effect on JDSP.
Check JDSP Telegram group for latest update!

**Comment by GiRiKoTTe** [comment]
Spectrum extension is one of the two features that keeps viper on my phone. Looking eagerly forward for its implementation in JamesDSP

**Comment by james34602** [comment]
That effect would be TBD now, since it waste CPU power on something human not sensitive to.

**Comment by GiRiKoTTe** [comment]
Very high frequencies are indeed psycho acoustically imperceptible. But harmonic excitement applied to higher frequencies does change the perception of "airiness" or "crispness" in the music.
But I confess that I have no idea how it affects the battery.

**Comment by james34602** [comment]
I have long time not following up old posts.

Latest JDSP has EEL, a user-programmable processor allows user to program their own effect with C-liked language.

Viper reverse engineering project been almost fully completed, user can now use JDSP to perform complete replication of Viper effect with EEL
