### ISSUE TITLE
Parametric equalizer

### ISSUE THREAD

**Issue by Harold999** [james34602/JamesDSPManager#16]
Hi James, would it be possible to create parametric eq options, like the possibility of adding custom frequencies and Q factor?

**Comment by Harold999** [comment]
James, the curve that your EQ is showing, is that the true curve or is reality different?

**Comment by james34602** [comment]
It is true curve, I generate impulse response from testing C code, and check via Matlab fvtool.

**Comment by Taudris** [comment]
If you don’t need realtime adjustment on your phone, you can use rePhase on a PC to generate impulse responses with whatever EQ settings you want. I’ve been able to get acceptable results with 2048 samples for 44.1 KHz, 8ms centering, and minimum phase. You can also use rePhase with Room EQ Wizard if you’re using the EQ for calibration.

**Comment by james34602** [comment]
@Taudris had put forward a accurate and customized solution
