### ISSUE TITLE
Dialogue enhancer - Feature request 

### ISSUE THREAD

**Issue by GiRiKoTTe** [james34602/JamesDSPManager#21]
Dolby Atmos for phones has a feature called "Dialogue enhancer". It makes for a better movie watching experience. It would be great to see the same or similar feature on JamesDSP. 

What do you reckon Dolby does to achieve that effect? 

Off topic but I must compliment you and team on the astoundingly good TruCentre surround effect with the angle controls.

**Comment by james34602** [comment]
There will be a vocal enhancer. JDSP would worth to rename to JDSP AI(Artificial intelligence) since then.
For TruCentre, even can't consider to a team at all, that's Joe0Bloggs, who provide digital filters to enhance my upmix module with decent quality improvements.

**Comment by GiRiKoTTe** [comment]
So, a vocal enhancer is far more complex than I imagined! Am I wrong to assume that that it's similar to "clarity" effect on Viper?

**Comment by james34602** [comment]
I'm not sure how other do the job, but I would use some cutting edge or somehow miracle methods.

**Comment by GiRiKoTTe** [comment]
Miracles *might* happen.😁
Once again, thanks for the amazing plug-in and prompt response to suggestions

**Comment by Littlemac123** [comment]
What about the Karaoke filter thats been built into vlc for years?

**Comment by james34602** [comment]
Most likely, it's a centre enhancement algorithm.

JDSP Stereo vocal enhancement already exist in a form of EEL script, as well as non-EEL form in JDSP spatial effect section
