### ISSUE TITLE
crash on sm-g9650

### ISSUE THREAD

**Issue by kmvan** [james34602/JamesDSPManager#22]
> Name : James DSP 
> Build version: 8.3 
> Build date: 2018-11-21 00:03:32 
> Current date: 2019-02-22 13:56:48 
> Device: Samsung SM-G9650 
>  
> Stack trace:  
> java.lang.RuntimeException: Unable to create service james.dsp.service.HeadsetService: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3552)
> 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
> 	at android.os.Handler.dispatchMessage(Handler.java:105)
> 	at android.os.Looper.loop(Looper.java:164)
> 	at android.app.ActivityThread.main(ActivityThread.java:6938)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
> Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at james.dsp.service.HeadsetService$JDSPModule.<init>(HeadsetService.java:78)
> 	at james.dsp.service.HeadsetService.onCreate(HeadsetService.java:512)
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3542)
> 	... 9 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.lang.reflect.Constructor.newInstance0(Native Method)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
> 	at james.dsp.service.HeadsetService$JDSPModule.<init>(HeadsetService.java:73)
> 	... 11 more
> Caused by: java.lang.RuntimeException: Cannot initialize effect engine for type: f98765f4-c321-5de6-9a45-123459495ab2 Error: -19
> 	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:425)
> 	... 14 more
>

**Comment by james34602** [comment]
wow, new phone, kind of new...
How to do instal the module?
Any custom stuff exist before installation?

**Comment by kmvan** [comment]
I installed from Magisk module :)
Not stuff yet before installation.

**Comment by james34602** [comment]
The UI part has almost discontinued, the de Witt team continuing to develop a new UI and installation system.
I contact them to obtain a beta test APK.
OR if you like join Telegram group: [https://t.me/jDSP_V4A](Group!)

**Comment by kmvan** [comment]
Got it.

**Comment by james34602** [comment]
You can contact me by email if you want to have a brand new test.

**Comment by geiszla** [comment]
Any news on this? I tried to install the latest beta (v3.0) from the Telegram group with and without V4A, old/new app with no success. It always crashes with the error `Cannot initialize effect engine for type:`.

**Comment by james34602** [comment]
The error is mostly caused by SELinux.
The latest JDSP should have get rid of stdc++ dependency, some device should able to use new JDSP without V4A.
