### ISSUE TITLE
How do I improve the audio performance by  james dsp ?

### ISSUE THREAD

**Issue by eromoe** [james34602/JamesDSPManager#25]
Hello, 
This my first time to install an audio module to my device (oneplus 6 ). 

Questions : 

### 1. Do I install correctly ?

There is only `ainur james dsp manager` in magisk module list, which faq refer to ` ainur audio`  https://forum.xda-developers.com/android/software/soundmod-ainur-audio-t3450516 . 
So I need install `ainur audio` at first , right? 
I am confused about what are these audio modules different from each other .

Have installed

- ainur audio
- audio compatibility pach   (I saw the faq said some music software would by pass someting audio layer , so this module here , I dont know if I need install this)
- ainur james dsp manager

by order .

Is this installation correct  or I miss something ?
Because I just feel the speaker become louder . 

Sorry I am not very familiar with audio knowledge ,  I think dsp is something like eq  but more powerful.
I haven't adjusted yet, trying to figure out how ainur audio is better than original . 

###  2.  Do I need a codec for my phone ?

I only  have my phone with sony 1000 xm2  , some inear headphones .

### 3.  Is it fine with bluetooth or better have cable connect to headphone ？

There is so less information about each audio module , it is very hard to understand the thing behind them, hard to figure out what is good for my situation .

**Comment by james34602** [comment]
1. I'm not familiar with those audio mods, so I don't know. But you talk about DSP, it's a bit vague and general, it can be anything process signal, equalizer is one of its application, it's implemented using DSP technique, there're categories of effects that enhance audio, for example, convolver can model almost any audio system, including compensating your headphone/speaker frequency response.
2. I recommend PowerAMP and Hiby music player, they both can be downloaded on Play store.
3. Bluetooth and headphone are both good for music playback, especially, Bluetooth sound quality is getting better this day.
