### ISSUE TITLE
Where should I put the .so file?

### ISSUE THREAD

**Issue by mechtifs** [james34602/JamesDSPManager#3]
I'm sorry that I cannot understand what you r meaning because of my pool English. The CPU is arm CPU, so where should I put the .so file in /system? /system/lib/ , /system/lib/soundfx/ or other directory? Should I put it with the armeabi-v7a folder? I'm waiting for your reply, thx!

**Comment by james34602** [comment]
Put it in /system/lib/soundfx/
Remember to put audio_effects.conf in to /system/vendor/etc, you can use previous release of audio_effects.conf

**Comment by mechtifs** [comment]
thx for your help！

**Comment by james34602** [comment]
Stay tuned!
