### ISSUE TITLE
Does JamesDSP limit the samplerate?

### ISSUE THREAD

**Issue by LuanHalaiko** [james34602/JamesDSPManager#31]
Hello! I've always had this question since I was told that Viper4android limits the output to **16bit 48khz** on any device. Does JamesDSP have something similar? the output of my device is **32bit 192khz**, I've checked that it supports **32bit** audio, but what about the **192khz samplerate**? thanks in advance.

**Comment by james34602** [comment]
Yes, JamesDSP support 192kHz sample rate, but the sample rate is determined by AudioFlinger.
Common config of AudioFlinger is 48kHz 16bit.

**Comment by LuanHalaiko** [comment]
Thanks for the quick reply, can I somehow change the config of AudioFlinger to output 192khz 32bit?

**Comment by james34602** [comment]
Some user claim change "mixer" setting using some kind of xml do exactly that, but I'm not sure the trick works or not.

**Comment by LuanHalaiko** [comment]
Hmm, I think I know what you mean. I've checked this and it truly is 192khz
32bit, I even did some logs. Thanks for the help!

Em sex., 25 de jun. de 2021 às 08:40, James Fung ***@***.***>
escreveu:
