### ISSUE TITLE
[Feature request] Set exact values into the equalizer

### ISSUE THREAD

**Issue by LuanHalaiko** [james34602/JamesDSPManager#32]
It's a bit hard to set an exact value in the graphic equalizer, l have the exact values for my headphones that I use on PC with equalizer APO and it would be great to transfer them to JamesDSP on android

![image](https://user-images.githubusercontent.com/16543796/129376581-f145bd52-3933-4125-915b-acea4a285df5.png)

**Comment by james34602** [comment]
The option already here, it's call Arbitrary Magnitude String Equalizer, you can directly copy the "GraphicEq:" data and directly paste data to JDSP Arbitrary Magnitude String Equalizer

**Comment by LuanHalaiko** [comment]
Oh I didn't know it could that, thanks for explaining it and sorry for opening a request without looking further into it.
