### ISSUE TITLE
Black screen -> closed on Redmi Note 8 Pro, Magisk 23.0, James DSP Manager from 17 Feb 2018 release

### ISSUE THREAD

**Issue by Harmonised7** [james34602/JamesDSPManager#34]
Issue:
Cannot launch DSP Manager on Redmi Note 8 Pro

No idea what's wrong. Not sure how to get a log. Installed through Magisk.

Edit: I tried both the Release, and download from Magisk. Magisk has version 4.2 9-8-2021, exact same issue.
Also, Stock OS

**Comment by james34602** [comment]
Android version is?

Highly likely outcome is no solution, sorry about that.
