### ISSUE TITLE
James DSP crashing on launch

### ISSUE THREAD

**Issue by furopi** [james34602/JamesDSPManager#37]
Hi,

I doubt there is a solution to my problem, but I thought I'd better ask first before going desperate...

Like the title says, James DSP is crashing on start. At first start it still asks for the permissions but then crashes after.

I'm on a Xiaomi Mi 11 (venus) with xiaomi.eu MIUI 13 (Android 12) ROM installed and Magisk 24.304. Any help very much appreciated. Thank you!

**Comment by pflanzenandi** [comment]
I have the same problem. The App is crashing on Android 12, but worked fine on Android 11.

**Comment by thegergo02** [comment]
Same, but with Redmi Note 11 and Android 11 (Magisk 24).

**Comment by james34602** [comment]
I'm sorry, I no longer use Android device since 2018 and I have plenty of works to do.

No chance I will be maintaining JDSP anymore.

**Comment by james34602** [comment]
I only back to core development of JDSP

Any Android related questions is still can't be answered, I feel like answer you are looking for already exist in Telegram group
