### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by therealahrion** [james34602/JamesDSPManager#4]
I'm just wondering why this app takes 100% control of the audio focus rather than being compatible with things like Samsung soundalive, DTS, dolby, dirachd, etc. 

The others seem to allow audiofocus to be shared.

**Comment by james34602** [comment]
This is probably due to replacing audio_effects.conf.
Would you provided your audio_effects.conf that compatible with other non-system effects?

**Comment by therealahrion** [comment]
I didn't replace the audio effects, I patched in your jdsp stuff

**Comment by therealahrion** [comment]
It just overrides the other effects. So it doesn't FC or anything but it literally doesn't allow other effects to work alongside it. When I disable the other effects work for the other apps. 

It's like it takes the audio focus away from over things else and overrides other apps.

**Comment by james34602** [comment]
Might be my phone is a special case...It is OnePlus 3T, my jamesdsp is not allow to 'Override' the basic system effect, and two effect work perfectly together

**Comment by therealahrion** [comment]
It overrides my Dolby Atmos effects as well as my Dirac Effects. 

Dolby Atmos usually has the Virtualizer going and works, but when this is enabled it does not move the virtualizer or allow the effects to work.

**Comment by james34602** [comment]
Currently, I have no solution for this.

**Comment by james34602** [comment]
This should be solved
