### ISSUE TITLE
Works around OpenSL ES?

### ISSUE THREAD

**Issue by qumuq-til** [james34602/JamesDSPManager#44]
Does the DSP somehow reroute audio to present in natively vs submitting it to OpenSL ES for output? I'm looking to fix sound degradation and dithering present with the default Android audio stack (as opposed to when certain music player apps access the audio hardware directly), but need no FX at all.

**Comment by james34602** [comment]
Android is not my expertise and I assume the answer is no.
At least, there is no robust solution for this.

I only make robust solution, not the solution that fix problem for specific device
