### ISSUE TITLE
Problem with Dynamic Range Compression

### ISSUE THREAD

**Issue by Radst0ne** [james34602/JamesDSPManager#5]
Everything works fine execpt compression. If turned on it gets awful loud, louder than highest setting. And changing the volume does not affect anything (even if volume is turned down completely )
Im running on lollipop (64bit), latest official release and mtk 6753 (arm v8-a)
If more Information is needed just tell me

**Comment by james34602** [comment]
Yes.
I didn't work that great, because it depend on getting system volume level from API since Cyanogenmod.
This is buggy, feature will be re-written...

**Comment by james34602** [comment]
Problem should solved in new update

**Comment by Radst0ne** [comment]
Cool! Keep the great work up!
