### ISSUE TITLE
Does not work with online streaming application Soundcloud, Youtube

### ISSUE THREAD

**Issue by ikillcypher2** [james34602/JamesDSPManager#7]
hi it works fine with the stock android music player, but it Does not work with online streaming application Soundcloud, Youtube.

**Comment by james34602** [comment]
Yes, I will not support this feature. This could be done by creating global sessionId on 0 when starting JamesDSP service, like Viper4Android.
This is a unstable feature, trust me, I have test this, some of my devices not working, so I will not publish this.
If you pursue high quality audio, you should go PowerAMP.
