### ISSUE TITLE
Does this work on modified rom Like MIUI

### ISSUE THREAD

**Issue by AKprisonER** [james34602/JamesDSPManager#9]
Like can we create apk from this source and just install like other apps ?
 or James DSP is only available thru custom ROM or Rooted mobiles ?

**Comment by james34602** [comment]
I'm not sure about at all, it should work on MIUI, it depend on how your device manufacturer modify their audio framework.
It is designed for AOSP 5.x - 7.x non custom ROM. Rooting is also not required, as you only need a recovery to put JDSP files into system.
But many reports it work fine on others ROM(Stock Samsung, Stock Google devices, Stock XIAOMI, Stock Motorola).
Some ROM are guarantee to be not working, like stock HUAWEI, and stock HTC, if you want this phone works, custom ROM is needed.

**Comment by AKprisonER** [comment]
I was unaware about this. 
I was trying to use the generated apk directly on phone like other apps.
Like installing normal app

**Comment by james34602** [comment]
Sadly, Google doesn't provide a non system custom audio effect.
For convenient installation, you can check my XDA thread for more details, some great people make Magisk module to let this install much easier.
If you want to use this without modifying system, then you can take core code and make a custom music player, but this far more difficult.

**Comment by Zackptg5** [comment]
@AKprisonER 
Ahrion and I have made a full installer/uninstaller for jdsp here: https://github.com/therealahrion/JamesDSPManager

I've been looking for a MIUI tester if you'd be interested
